################################################################################
## SET ABODE STATE
################################################################################

- id: set_abode_state
  alias: Set Abode State
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.abode_status
  action:
    service_template: >
      alarm_control_panel.alarm_{{ trigger.to_state.state }}
    entity_id: alarm_control_panel.abode

################################################################################
## SET LIGHT SCENES (LIFX + HUE)
################################################################################

- id: set_light_scenes
  alias: Set Light Scenes
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.lights_scene
  action:
    - service: scene.turn_on
      data_template:
        entity_id: scene.{{ trigger.to_state.state|lower|replace(" ", "_") }}_lifx
    - service: hue.hue_activate_scene
      data_template:
        group_name: "Dining Room"
        scene_name: "{{ trigger.to_state.state }} Hue"
    - service: hue.hue_activate_scene
      data_template:
        group_name: "Living Room"
        scene_name: "{{ trigger.to_state.state }} Hue"
    - service: hue.hue_activate_scene
      data_template:
        group_name: "Bathroom"
        scene_name: "{{ trigger.to_state.state }} Hue"
    - service: hue.hue_activate_scene
      data_template:
        group_name: "Kitchen"
        scene_name: "{{ trigger.to_state.state }} Hue"
    - service: hue.hue_activate_scene
      data_template:
        group_name: "Bedroom"
        scene_name: "{{ trigger.to_state.state }} Hue"

################################################################################
## SLEEPYTIME
################################################################################

- id: sleepytime
  alias: Sleepytime
  initial_state: true
  trigger:
    platform: mqtt
    topic: dash/pressed
    payload: active
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: state
        entity_id: media_player.kodi
        state: idle
  action:
    service: scene.turn_on
    entity_id: scene.sleepytime

################################################################################
## MORNING ROUTINE
################################################################################

- id: wakeytime
  alias: Wakeytime
  initial_state: true
  trigger:
    platform: mqtt
    topic: dash/pressed
    payload: active
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: scene.turn_on
    entity_id: scene.wakeytime

################################################################################
## ARM ALARM AND TURNOFF LIGHTS WHEN CAR LEAVES
################################################################################

- id: set_away_mode
  alias: Set Away Mode
  initial_state: true
  trigger:
    platform: zone
    entity_id: device_tracker.honda_accord_cpe
    zone: zone.home
    event: leave
  action:
    service: scene.turn_on
    entity_id: scene.out_of_the_house

################################################################################
## BEDROOM OSMC DIMS LIGHTS
################################################################################

- id: upstairs_osmc_playing
  alias: Upstairs OSMC Playing
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: playing
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: scene.turn_on
    entity_id: scene.upstairs_osmc_playing

################################################################################
## LIVING ROOM MULTISENSOR LED CHANGE ON MOTION
################################################################################

- id: living_room_motion_led_on
  alias: Living Room Motion LED ON
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.living_room_motion_status
    from: None
    to: Motion Detected
  action:
    service: light.turn_on
    entity_id: light.living_room_sensor_led

- id: living_room_motion_led_off
  alias: Living Room Motion LED OFF
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.living_room_motion_status
    from: Motion Detected
    to: None
  action:
    service: light.turn_off
    entity_id: light.living_room_sensor_led

################################################################################
## KITCHEN MULTISENSOR LED CHANGE ON MOTION
################################################################################

- id: kitchen_motion_led_on
  alias: Kitchen Motion LED ON
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion_status
    from: None
    to: Motion Detected
  action:
    service: light.turn_on
    entity_id: light.kitchen_sensor_led

- id: kitchen_motion_led_off
  alias: Kitchen Motion LED OFF
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion_status
    from: Motion Detected
    to: None
  action:
    service: light.turn_off
    entity_id: light.kitchen_sensor_led

################################################################################
## OFFICE MULTISENSOR LED CHANGE ON MOTION
################################################################################

- id: office_motion_led_on
  alias: Office Motion LED ON
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.office_motion_status
    from: None
    to: Motion Detected
  action:
    service: light.turn_on
    entity_id: light.office_sensor_led

- id: office_motion_led_off
  alias: Office Motion LED OFF
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.office_motion_status
    from: Motion Detected
    to: None
  action:
    service: light.turn_off
    entity_id: light.office_sensor_led

################################################################################
## KITCHEN MULTISENSOR LIGHTS ON MOTION
################################################################################

- id: kitchen_motion_led_on
  alias: Kitchen Motion Lights ON
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion_status
    from: None
    to: Motion Detected
  action:
    service: homeassistant.turn_on
    entity_id: group.kitchen

- id: kitchen_motion_led_off
  alias: Kitchen Motion Lights OFF
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion_status
    from: Motion Detected
    to: None
    for:
      minutes: 1
  action:
    service: homeassistant.turn_off
    entity_id: group.kitchen
