- platform: generic_thermostat
  name: Upstairs AC
  ac_mode: true
  heater: switch.upstairs_ac_power
  target_sensor: sensor.bedroom_heat_index
  min_temp: 60
  max_temp: 120
  target_temp: 100
  tolerance: 0.5
  min_cycle_duration:
    seconds: 20
  keep_alive:
    minutes: 1
