homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Phoenix
  customize: !include customize.yaml
  customize_domain:
    light:
      icon: 'mdi:lightbulb-on-outline'
  customize_glob: {}
frontend:
  javascript_version: latest
http:
  api_password: !secret hass_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  login_attempts_threshold: 5
  ip_ban_enabled: true
  base_url: !secret base_url
config: null
updater: null
discovery: null
hassio:
conversation: null
history: null
recorder: !include recorder.yaml
logbook: null
system_log: null
ios: null
map: null
sun: null
camera: !include camera.yaml
sensor: !include sensor.yaml
tts:
  platform: google
mqtt: !include mqtt.yaml
zwave:
  usb_path: /dev/ttyUSB0
ifttt:
  key: !secret ifttt_key
device_tracker: !include device_tracker.yaml
light: !include light.yaml
switch: !include switch.yaml
notify: !include notify.yaml
alert: !include alert.yaml
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
# climate: !include climate.yaml
media_player: !include media_player.yaml
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: true
input_select: !include input_select.yaml
group: !include groups.yaml
automation: !include automations.yaml
scene: !include scene.yaml
zone:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 100
  icon: mdi:domain
emulated_hue: !include emulated_hue.yaml
# influxdb:
#   host: !secret influx_host
#   username: !secret influx_user
#   password: !secret influx_password
python_script: null
abode:
  username: !secret sunnys_email
  password: !secret abode_password
  name: Abode
shopping_list: null
