################################################################################
## AUTOMATIC
################################################################################

- platform: automatic
  client_id: !secret automatic_client_id
  secret: !secret automatic_secret
  username: !secret sunnys_email
  password: !secret automatic_password
