################################################################################
## BEDROOM OSMC
################################################################################

# - platform: kodi
#   name: OSMC Bedroom
#   host: !secret osmc_bedroom_ip
#   username: !secret osmc_bedroom_username
#   password: !secret osmc_bedroom_password
#   turn_off_action: suspend

################################################################################
## LIVING ROOM OSMC
################################################################################

# - platform: kodi
#   name: OSMC Main
#   host: !secret osmc_main_ip
#   username: !secret osmc_main_username
#   password: !secret osmc_main_password
#   turn_off_action: suspend

################################################################################
## SPOTIFY
################################################################################

- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
