################################################################################
## MOON
################################################################################

- platform: moon

################################################################################
## LAST.FM
################################################################################

# - platform: lastfm
#   api_key: !secret lastfm_api_key
#   users:
#     - Ynnus
#   scan_interval: 15

################################################################################
## WEATHER UNDERGROUND
################################################################################

- platform: wunderground
  api_key: !secret wu_api_key
  monitored_conditions:
    - alerts
    - dewpoint_f
    - feelslike_f
    - heat_index_f
    - elevation
    - location
    - observation_time
    - precip_1hr_in
    - precip_today_in
    - pressure_in
    - pressure_mb
    - pressure_trend
    - relative_humidity
    - station_id
    - solarradiation
    - temp_f
    - UV
    - visibility_mi
    - weather
    - wind_degrees
    - wind_dir
    - wind_gust_mph
    - wind_mph

################################################################################
## SSL CERTIFICATE CHECK
################################################################################

- platform: cert_expiry
  host: !secret base_url

################################################################################
## FAST.COM SPEED CHECK
################################################################################

- platform: fastdotcom
  minute:
    - 0
    - 30

################################################################################
## BEDROOM ROOM MULTISENSOR
################################################################################

- platform: mqtt
  state_topic: "sensors/bedroom"
  name: "Bedroom Temperature"
  unit_of_measurement: °F
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: "sensors/bedroom"
  name: "Bedroom Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: "sensors/bedroom"
  name: "Bedroom LUX"
  unit_of_measurement: LUX
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "sensors/bedroom"
  name: "Bedroom Motion Status"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "sensors/bedroom"
  name: "Bedroom Heat Index"
  unit_of_measurement: °F
  value_template: '{{ value_json.heatIndex }}'

################################################################################
## LIVING ROOM MULTISENSOR
################################################################################

- platform: mqtt
  state_topic: "/living_room_multisensor/Climate/Temperature"
  name: "Living Room Temperature"
  unit_of_measurement: °F

- platform: mqtt
  state_topic: "/living_room_multisensor/Climate/Humidity"
  name: "Living Room Humidity"
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "/living_room_multisensor/Motion/Switch"
  name: "Living Room Motion Status"
  value_template: '{{ value|replace("0","None")|replace("1","Motion Detected") }}'

- platform: template
  sensors:
    living_room_heat_index:
      friendly_name: "Living Room Heat Index"
      entity_id: sensor.living_room_temperature, sensor.living_room_humidity
      unit_of_measurement: °F
      value_template: >-
        {% set vars = {
          "c1": -42.379,
          "c2": 2.04901523,
          "c3": 10.14333127,
          "c4": -0.22475541,
          "c5": -0.00683783,
          "c6": -0.05481717,
          "c7": 0.00122874,
          "c8": 0.00085282,
          "c9": -0.00000199,
          "t": states.sensor.living_room_temperature.state|float,
          "h": states.sensor.living_room_humidity.state|float
        } %}

        {% set heatIndex = 0.5 * (vars.t + 61 + (vars.t - 68) * 1.2 + vars.h * 0.094) %}

        {% if vars.t >= 80 %}

          {% set heatIndexBase = vars.c1 + vars.c2 * vars.t + vars.c3 * vars.h + vars.c4 * vars.t * vars.h + vars.c5 * vars.t * vars.t + vars.c6 * vars.h * vars.h + vars.c7 * vars.t * vars.t * vars.h + vars.c8 * vars.t * vars.h * vars.h +vars.c9 * vars.t * vars.t * vars.h * vars.h %}

          {% if vars.h < 13 and vars.t <= 112 %}

            {% set heatIndex = heatIndexBase - (13 - vars.h) / 4 * root((17 - abs(vars.t - 95)) / 17) %}

          {% elif vars.h > 85 and vars.t <= 87 %}

            {% set heatIndex = heatIndexBase + ((vars.h - 85) / 10) * ((87 - vars.t) / 5) %}

          {% else %}

            {% set heatIndex = heatIndexBase %}

          {%- endif %}

        {%- endif %}

        {{ heatIndex|round(2) }}

################################################################################
## OFFICE MULTISENSOR
################################################################################

- platform: mqtt
  state_topic: "/office_multisensor/Climate/Temperature"
  name: "Office Temperature"
  unit_of_measurement: °F

- platform: mqtt
  state_topic: "/office_multisensor/Climate/Humidity"
  name: "Office Humidity"
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "/office_multisensor/Motion/Switch"
  name: "Office Motion Status"
  value_template: '{{ value|replace("0","None")|replace("1","Motion Detected") }}'

- platform: template
  sensors:
    office_heat_index:
      friendly_name: "Office Heat Index"
      entity_id: sensor.office_temperature, sensor.office_humidity
      unit_of_measurement: °F
      value_template: >-
        {% set vars = {
          "c1": -42.379,
          "c2": 2.04901523,
          "c3": 10.14333127,
          "c4": -0.22475541,
          "c5": -0.00683783,
          "c6": -0.05481717,
          "c7": 0.00122874,
          "c8": 0.00085282,
          "c9": -0.00000199,
          "t": states.sensor.office_temperature.state|float,
          "h": states.sensor.office_humidity.state|float
        } %}

        {% set heatIndex = 0.5 * (vars.t + 61 + (vars.t - 68) * 1.2 + vars.h * 0.094) %}

        {% if vars.t >= 80 %}

          {% set heatIndexBase = vars.c1 + vars.c2 * vars.t + vars.c3 * vars.h + vars.c4 * vars.t * vars.h + vars.c5 * vars.t * vars.t + vars.c6 * vars.h * vars.h + vars.c7 * vars.t * vars.t * vars.h + vars.c8 * vars.t * vars.h * vars.h +vars.c9 * vars.t * vars.t * vars.h * vars.h %}

          {% if vars.h < 13 and vars.t <= 112 %}

            {% set heatIndex = heatIndexBase - (13 - vars.h) / 4 * root((17 - abs(vars.t - 95)) / 17) %}

          {% elif vars.h > 85 and vars.t <= 87 %}

            {% set heatIndex = heatIndexBase + ((vars.h - 85) / 10) * ((87 - vars.t) / 5) %}

          {% else %}

            {% set heatIndex = heatIndexBase %}

          {%- endif %}

        {%- endif %}

        {{ heatIndex|round(2) }}

################################################################################
## KITCHEN MULTISENSOR
################################################################################

- platform: mqtt
  state_topic: "sensors/kitchen"
  name: "Kitchen Temperature"
  unit_of_measurement: °F
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: "sensors/kitchen"
  name: "Kitchen Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: "sensors/kitchen"
  name: "Kitchen Motion Status"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "sensors/kitchen"
  name: "Kitchen Heat Index"
  unit_of_measurement: °F
  value_template: '{{ value_json.heatIndex }}'

################################################################################
## DINING ROOM MULTISENSOR
################################################################################

- platform: mqtt
  state_topic: "sensors/dining_room"
  name: "Dining Room Temperature"
  unit_of_measurement: °F
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: "sensors/dining_room"
  name: "Dining Room Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: "sensors/dining_room"
  name: "Dining Room Motion Status"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "sensors/dining_room"
  name: "Dining Room Heat Index"
  unit_of_measurement: °F
  value_template: '{{ value_json.heatIndex }}'

################################################################################
## CAMERAS
################################################################################

- platform: mqtt
  name: Living Room Status
  state_topic: "cameras/foscam/living_room/motion_status"

- platform: mqtt
  name: Living Room Motion
  state_topic: "cameras/foscam/living_room/motion_detect"

- platform: mqtt
  name: Dining Room Status
  state_topic: "cameras/foscam/dining_room/motion_status"

- platform: mqtt
  name: Dining Room Motion
  state_topic: "cameras/foscam/dining_room/motion_detect"

################################################################################
## NZBGet
################################################################################

- platform: nzbget
  host: !secret nzbget_ip
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
  - article_cache
  - average_download_rate
  - download_rate
  - free_disk_space
  - uptime
