################################################################################
## AMAZON DASH
################################################################################

- platform: mqtt
  name: Amazon Dash
  command_topic: dash/pressed
  state_topic: dash/pressed
  payload_on: active
  payload_off: inactive

################################################################################
## CAMERA MONITORING
################################################################################

- platform: mqtt
  name: Camera Monitoring
  command_topic: cameras/foscam
  state_topic: cameras/foscam
  payload_on: arm
  payload_off: disarm
  retain: true

################################################################################
## BROADLINK
################################################################################

- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac_address
  friendly_name: Broadlink
  switches:
    upstairs_ac_power:
      friendly_name: Upstairs AC Power
      command_off: 'JgB2AG4yEAsQCw8mEAsPJhALEAoQCxAmDyYQChALEAsQJg8mEAoQCxALEAoQCxALEAoQCxALEAsPCxALEAsPJhALEAoQCxALEAoQCxALECYPCxALDwsQCxAmDwsQCxAKEAsQCxAKECYQCw8mECYPJhAlECYPJhAADQUAAA=='
      command_on: 'JgAGAWs1Dg0NDg0oDQ4NKA0ODQ4NDQ4oDSgNDg0NDg0NKA4oDQ4NDQ0ODQ4NDQ4NDQ4NDQ4NDQ4NDQ4NDQ4NKA0ODQ4NDQ4NDQ4NDQ4NDSgODQ0ODQ0ODQ0pDSgNKA4oDSgNKA4oDSgNDg0ODSgNDg0NDg0NDg0NDg0NDg0NDigNKA4NDQ4NKA0ODQ0ODQ0oDg0NDg0oDSkNDQ4NDQ4NDQ4NDQ4NDQ4oDQ4NDQ0ODQ4NDQ4NDQ4NDQ4NDQ4NDQ4NDQ4NDQ4NDQ4NDg0NDg0NDg0NDg0NDg0NDg0NDg0NDg0NDg0ODQ0NDg0ODQ0ODQ0ODSgNDg0NDigNDg0oDSgOKA0NDg0NDg0ADQUAAA=='
