homeassistant:

  ################################################################################
  ## CUSTOMIZE
  ################################################################################

  customize:

    ################################################################################
    ## NODE ANCHORS
    ################################################################################

    package.node_anchors:
      customize: &customize
        package: 'bedroom_multisensor'

      hidden: &hidden
        <<: *customize
        hidden: true
        emulated_hue_hidden: true

################################################################################
## SENSORS
################################################################################

sensor:

  - platform: mqtt
    state_topic: "sensors/bedroom"
    name: "Bedroom Temperature"
    unit_of_measurement: °F
    value_template: '{{ value_json.temperature }}'

  - platform: mqtt
    state_topic: "sensors/bedroom"
    name: "Bedroom Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity }}'

  - platform: mqtt
    state_topic: "sensors/bedroom"
    name: "Bedroom LUX"
    unit_of_measurement: LUX
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "sensors/bedroom"
    name: "Bedroom Motion Status"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "sensors/bedroom"
    name: "Bedroom Heat Index"
    unit_of_measurement: °F
    value_template: '{{ value_json.heatIndex }}'
