homeassistant:

  ################################################################################
  ## CUSTOMIZE
  ################################################################################

  customize:

    ################################################################################
    ## NODE ANCHORS
    ################################################################################

    package.node_anchors:
      customize: &customize
        package: 'abode'

      hidden: &hidden
        <<: *customize
        hidden: true
        emulated_hue_hidden: true

################################################################################
## AUTOMATION - SET ABODE STATE
################################################################################

automation:
- id: set_abode_state
  alias: Set Abode State
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.abode_status
  action:
    service_template: >
      alarm_control_panel.alarm_{{ trigger.to_state.state }}
    entity_id: alarm_control_panel.abode

################################################################################
## INPUT SELECT
################################################################################

input_select:
  abode_status:
    name: Abode Status
    options:
      - disarm
      - arm_home
      - arm_away
    initial: disarm
    icon: mdi:security-home

################################################################################
## ABODE PLATFORM
################################################################################

abode:
  username: !secret sunnys_email
  password: !secret abode_password
  name: Abode
