homeassistant:

  ################################################################################
  ## CUSTOMIZE
  ################################################################################

  customize:

    ################################################################################
    ## NODE ANCHORS
    ################################################################################

    package.node_anchors:
      customize: &customize
        package: 'abode'

      hidden: &hidden
        <<: *customize
        hidden: true
        emulated_hue_hidden: true

################################################################################
## IFTTT PLATFORM
################################################################################

ifttt:
  key: !secret ifttt_key
