homeassistant:

  ################################################################################
  ## CUSTOMIZE
  ################################################################################

  customize:

    ################################################################################
    ## NODE ANCHORS
    ################################################################################

    package.node_anchors:
      customize: &customize
        package: 'network'

      hidden: &hidden
        <<: *customize
        hidden: true
        emulated_hue_hidden: true

################################################################################
## SENSORS
################################################################################

sensor:

  ################################################################################
  ## SSL CERTIFICATE CHECK
  ################################################################################

  - platform: cert_expiry
    host: !secret base_url

  ################################################################################
  ## FAST.COM SPEED CHECK
  ################################################################################

  - platform: fastdotcom
    minute:
      - 0
      - 30
