homeassistant:

  ################################################################################
  ## CUSTOMIZE
  ################################################################################

  customize:

    ################################################################################
    ## NODE ANCHORS
    ################################################################################

    package.node_anchors:
      customize: &customize
        package: 'abode'

      hidden: &hidden
        <<: *customize
        hidden: true
        emulated_hue_hidden: true

################################################################################
## INPUT SELECT
################################################################################

input_select:

  ################################################################################
  ## SCENES LIST
  ################################################################################

  lights_scene:
    name: Lights Scene
    options:
      - Out of the House
      - Sleepytime
      - Wakeytime
      - Evening
      - Upstairs OSMC Playing
      - Bedroom Evening Chillin

################################################################################
## SCENES
################################################################################

scene:

  ################################################################################
  ## OUT OF THE HOUSE
  ################################################################################

  - name: Out of the House
    entities:

      # Alarm
      input_select.abode_status:
        option: arm_away

      # Lights
      input_select.lights_scene:
        option: Out of the House

      group.dining_room: off
      group.bedroom: off
      group.living_room: off
      group.office: off
      group.kitchen: off
      group.bathroom: off

      # Climate
      climate.nest:
        operation_mode: eco

  ################################################################################
  ## SLEEPYTIME
  ################################################################################

  - name: Sleepytime
    entities:

      # Alarm
      input_select.abode_status:
        option: arm_home

      # Lights
      input_select.lights_scene:
        option: Sleepytime

      light.reading_lamp:
        state: on
        brightness: 5
        xy_color: [0.6695,0.326]
      light.foyer:
        state: on
        brightness: 5
        xy_color: [0.6695,0.326]
      light.right_bed: off
      light.closet: off
      switch.stairway_switch: off
      group.dining_room: off
      group.living_room: off
      group.office: off
      group.kitchen: off
      group.bathroom: off

      # Climate
      climate.nest:
        operation_mode: eco

  ################################################################################
  ## WAKEYTIME
  ################################################################################

  - name: Wakeytime
    entities:

      # Alarm
      input_select.abode_status:
        option: disarm

      # Lights
      input_select.lights_scene:
        option: Wakeytime

      group.dining_room: off
      group.bedroom:
        state: off
      switch.stairway_switch: off
      group.living_room: off
      group.office: off
      group.kitchen: off
      group.bathroom: off

      # Climate
      climate.nest:
        operation_mode: cool

  ################################################################################
  ## EVENING
  ################################################################################

  - name: Evening
    entities:

      # Alarm
      input_select.abode_status:
        option: disarm

      # Lights
      input_select.lights_scene:
        option: Evening

      # Climate
      climate.nest:
        operation_mode: cool

  ################################################################################
  ## UPSTAIRS OSMC PLAYING
  ################################################################################

  - name: Upstairs OSMC Playing
    entities:

      # Alarm
      input_select.abode_status:
        option: arm_home

      # Lights
      input_select.lights_scene:
        option: Upstairs OSMC Playing

      group.bedroom:
        state: on
        brightness: 20
        color_temp: 438

  ################################################################################
  ## BEDROOM EVENING CHILLIN
  ################################################################################

  - name: Bedroom Evening Chillin
    entities:

      # Alarm
      input_select.abode_status:
        option: arm_home

      # Lights
      input_select.lights_scene:
        option: Bedroom Evening Chillin

      group.bedroom:
        state: on
        brightness: 143
        color_temp: 438
      switch.stairway_switch: on
