homeassistant:

  ################################################################################
  ## CUSTOMIZE
  ################################################################################

  customize:

    ################################################################################
    ## NODE ANCHORS
    ################################################################################

    package.node_anchors:
      customize: &customize
        package: 'scene_generator'

      hidden: &hidden
        <<: *customize
        hidden: true
        emulated_hue_hidden: true

################################################################################
## FILE SAVING
################################################################################

notify:

  - name: scene_generator
    platform: file
    filename: generated_scene.yaml
    timestamp: false
