homeassistant:

  ################################################################################
  ## CUSTOMIZE
  ################################################################################

  customize:

    ################################################################################
    ## NODE ANCHORS
    ################################################################################

    package.node_anchors:
      customize: &customize
        package: 'slack'

      hidden: &hidden
        <<: *customize
        hidden: true
        emulated_hue_hidden: true

################################################################################
## SLACK
################################################################################

notify:

  - name: Slack
    platform: slack
    api_key: !secret slack_api
    default_channel: '#home'
