homeassistant:

  ################################################################################
  ## CUSTOMIZE
  ################################################################################

  customize:

    ################################################################################
    ## NODE ANCHORS
    ################################################################################

    package.node_anchors:
      customize: &customize
        package: 'bedroom-multisensor'

      hidden: &hidden
        <<: *customize
        hidden: true
        emulated_hue_hidden: true

################################################################################
## MEDIA PLAYERS
################################################################################

media_player:

  ################################################################################
  ## SPOTIFY
  ################################################################################

  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
